In [1]:
%matplotlib inline
import pandas as pd
import utils

In [2]:
raw_data = utils.get_socrata_data("https://data.dcpcsb.org/resource/gi8f-g6am.json")
chi_charter = pd.DataFrame(raw_data)

Got https://data.dcpcsb.org/resource/gi8f-g6am.json?%24offset=0&%24limit=50000

# My dataset consists of Chicago charter school data. I hope to use Jupyter to look at this information in a different and, hopefully, glean some new details from it.

In [3]:
chi_charter.head()

,_1,_10,_11,_12,_2,_2013_pmf_score,_2013_pmf_tier,_3,_4,_5,...,street_address,street_address_address,street_address_city,street_address_state,street_address_zip,total_number_of_names_on_the_wait_list,total_number_of_seats_available,ungraded,ward,website
0,NaN,NaN,NaN,NaN,NaN,NaN,Untiered,NaN,6,0,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
1,0,NaN,NaN,NaN,0,0.43,2,8,2,0,...,NaN,NaN,NaN,NaN,NaN,17,NaN,NaN,NaN,NaN
2,68,NaN,NaN,NaN,47,NaN,Untiered,57,23,12,...,NaN,NaN,NaN,NaN,NaN,908,NaN,NaN,NaN,NaN
3,54,NaN,NaN,NaN,70,0.62,2,47,23,7,...,NaN,NaN,NaN,NaN,NaN,753,NaN,NaN,NaN,NaN
4,55,NaN,NaN,NaN,56,NaN,Untiered,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,380,NaN,NaN,NaN,NaN

In [4]:
chi_charter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 32 columns):
_1                                        149 non-null object
_10                                       44 non-null object
_11                                       31 non-null object
_12                                       24 non-null object
_2                                        144 non-null object
_2013_pmf_score                           169 non-null object
_2013_pmf_tier                            340 non-null object
_3                                        133 non-null object
_4                                        115 non-null object
_5                                        119 non-null object
_6                                        124 non-null object
_7                                        101 non-null object
_8                                        93 non-null object
_9                                        53 non-null object
adult_ed_ged_programs                     6 non-null object
k                                         151 non-null object
name_of_school                            340 non-null object
phone_number                              222 non-null object
pk3                                       149 non-null object
pk4                                       164 non-null object
school_id                                 218 non-null object
school_year                               340 non-null object
street_address                            215 non-null object
street_address_address                    215 non-null object
street_address_city                       114 non-null object
street_address_state                      112 non-null object
street_address_zip                        213 non-null object
total_number_of_names_on_the_wait_list    319 non-null object
total_number_of_seats_available           134 non-null object
ungraded                                  1 non-null object
ward                                      224 non-null object
website                                   221 non-null object
dtypes: object(32)
memory usage: 42.5+ KB

In [5]:
chi_charter.total_number_of_names_on_the_wait_list.value_counts().reset_index()

    index  total_number_of_names_on_the_wait_list
0       0                                      32
1       1                                      10
2      38                                       7
3       7                                       6
4      12                                       5
5       5                                       5
6       4                                       5
7      33                                       4
8       6                                       4
9       2                                       4
10     42                                       4
11      9                                       3
12      3                                       3
13    308                                       3
14     26                                       3
15     28                                       3
16     11                                       3
17     13                                       3
18     35                                       3
19     30                                       3
20    111                                       3
21    114                                       3
22     44                                       3
23     83                                       3
24    184                                       2
25     43                                       2
26    196                                       2
27     40                                       2
28    126                                       2
29     46                                       2
..    ...                                     ...
158   150                                       1
159   290                                       1
160    45                                       1
161  1381                                       1
162   221                                       1
163   371                                       1
164   720                                       1
165  1388                                       1
166   870                                       1
167   537                                       1
168   194                                       1
169   197                                       1
170   608                                       1
171   553                                       1
172    47                                       1
173   835                                       1
174    48                                       1
175   256                                       1
176    71                                       1
177   733                                       1
178   944                                       1
179   237                                       1
180    80                                       1
181   234                                       1
182   113                                       1
183   239                                       1
184   390                                       1
185    88                                       1
186  1202                                       1
187   217                                       1

[188 rows x 2 columns]

In [6]:
chi_charter.total_number_of_names_on_the_wait_list.describe()

count     319
unique    188
top         0
freq       32
Name: total_number_of_names_on_the_wait_list, dtype: object

In [8]:
chi_charter.total_number_of_seats_available.plot.bar()

TypeError: Empty 'DataFrame': no numeric data to plot

In [9]:
chi_charter.name_of_school.sum()

u"Excel Academy PCS \u2013 LEADFriendship PCS \u2013 Armstrong AmosCreative Minds International PCSDC Bilingual PCSDC Prep PCS \u2013 Benning ElementaryAcademy of Hope Adult PCSAppleTree Early Learning PCS \u2013 Columbia HeightsAppleTree Early Learning PCS \u2013 SoutheastAppleTree Early Learning PCS \u2013 Lincoln ParkAppleTree Early Learning PCS \u2013 Oklahoma AveAppleTree Early Learning PCS \u2013 SouthwestBASIS DC PCSBridges PCSBriya PCSCapital City PCS \u2013 High SchoolCapital City PCS \u2013 Lower SchoolCarlos Rosario International PCSCedar Tree Academy PCSCenter City PCS \u2013 BrightwoodCenter City PCS \u2013 Congress HeightsDC Prep PCS \u2013 Benning MiddleDC Prep PCS \u2013 Edgewood ElementaryDemocracy Prep Congress Heights PCSDistrict of Columbia International School (Chinese Language Program)District of Columbia International School (French Language Program)District of Columbia International School (Spanish Language Program)E.L. Haynes PCS \u2013 Elementary SchoolE.L. Haynes PCS \u2013 High SchoolE.L. Haynes PCS \u2013 Middle SchoolEarly Childhood Academy PCSElsie Whitlow Stokes Community Freedom PCSExcel Academy PCS \u2013 DREAMFriendship PCS \u2013 Blow-Pierce ElementaryFriendship PCS \u2013 Blow-Pierce MiddleFriendship PCS \u2013 Chamberlain ElementaryFriendship PCS \u2013 Chamberlain MiddleFriendship PCS \u2013 Collegiate AcademyFriendship PCS \u2013 Southeast Elementary AcademyFriendship PCS \u2013 Technology Preparatory AcademyFriendship PCS \u2013 Woodridge ElementaryFriendship PCS \u2013 Woodridge MiddleHoward University Middle School of Mathematics and Science PCSIdeal Academy PCSKIPP DC \u2013 AIM Academy PCSKIPP DC \u2013 Arts & Technology Academy PCSKIPP DC \u2013 College Preparatory PCSKIPP DC \u2013 Connect Academy PCSKIPP DC \u2013 Discover Academy PCSKIPP DC \u2013 Grow Academy PCSKIPP DC \u2013 Heights Academy PCSKIPP DC \u2013 KEY Academy PCSKIPP DC \u2013 LEAP Academy PCSKIPP DC \u2013 Lead Academy PCSKIPP DC \u2013 Northeast Academy PCSKIPP DC \u2013 Promise Academy PCSKIPP DC \u2013 Quest Academy PCSKIPP DC \u2013 Spring Academy PCSKIPP DC \u2013 Valor Academy PCSKIPP DC \u2013 WILL Academy PCSLAYC Career Academy PCSLatin American Montessori Bilingual PCSLee Montessori PCSMary McLeod Bethune Day Academy PCSMaya Angelou PCS \u2013 Young Adult Learning CenterMeridian Public Charter SchoolMundo Verde Bilingual PCSThe Next Step/El Pr\xf3ximo Paso PCSPaul PCS \u2013 International High SchoolPotomac Preparatory PCSSEED PCS of Washington, DCShining Stars Montessori Academy PCSSomerset Preparatory Academy PCSSt. Coletta Special Education PCSThurgood Marshall Academy PCSTwo Rivers PCSTwo Rivers PCS at YoungWashington Global Public Charter SchoolWashington Latin PCS \u2013 Middle SchoolWashington Latin PCS \u2013 Upper SchoolWashington Yu Ying PCSWilliam E. Doar Jr. (WEDJ) PCS for the Performing ArtsEagle Academy PCS \u2013 The Eagle Center at McGogneyCapital City PCS \u2013 Middle SchoolSela PCSThe Children's Guild DC Public Charter SchoolDC Prep PCS \u2013 Anacostia ElementaryHarmony DC PCS \u2013 School of ExcellenceKingsman Academy PCSMonument Academy PCSIngenuity Prep PCSHope Community PCS \u2013 LamondIDEA PCSWashington Mathematics Science Technology PCHSCenter City PCS \u2013 TrinidadC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Ch\xe1vez PrepCenter City PCS \u2013 Capitol HillPerry Street Preparatory PCSC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Parkside High SchoolDC Prep PCS \u2013 Edgewood MiddleRoots PCSC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Capitol HillEagle Academy PCS \u2013 New Jersey AvenueFriendship PCS \u2013 OnlineCommunity College Preparatory Academy PCSAchievement Preparatory Academy PCS \u2013 MiddleAchievement Preparatory Academy PCS \u2013 ElementaryNational Collegiate Preparatory PCHSCenter City PCS \u2013 PetworthDC Scholars PCSC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Parkside Middle SchoolHope Community PCS \u2013 TolsonRichard Wright PCS for Journalism and Media ArtsCenter City PCS \u2013 ShawInspired Teaching Demonstration PCSCapital City PCS \u2013 LowerSela PCSDC Bilingual PCSAppleTree Early Learning PCS \u2013 Lincoln ParkKIPP DC PCS \u2013 WILL AcademyAppleTree Early Learning PCS \u2013 Columbia HeightsRichard Wright PCS for Journalism and Media  ArtsCesar Chavez PCS for Public Policy \u2013 Parkside High SchoolHope Community PCS \u2013 TolsonRichard Wright PCS for Journalism and Media ArtsKIPP DC \u2013 Lead Academy PCSAcademy of Hope PCSWashington Mathematics Science Technology PCHSRoots PCSDC Scholars PCSWilliam E Doar, Jr PCSDC Preparatory Academy PCS \u2013 Benning ElementaryMundo Verde Bilingual PCSKIPP DC \u2013 WILL Academy PCSIDEA PCSSEED Public Charter School of Washington, DCCommunity Academy PCS \u2013 OnlineEagle Academy PCS \u2013 Congress HeightsDC Prep PCS \u2013 Edgewood MiddleCenter City PCS \u2013 BrightwoodFriendship PCS \u2013 Technology Preparatory HighWashington Mathematics Science Technology PCHSKIPP DC \u2013 College Preparatory PCSNational Collegiate Preparatory PCHSPaul PCS \u2013 International High SchoolFriendship PCS \u2013 Blow-Pierce MiddleElsie Whitlow Stokes Community Freedom PCS (French Language Program)Rocketship DC PCSBridges PCS - IEP ClassroomWashington Latin PCS \u2013 Middle SchoolDistrict of Columbia International School (Spanish Language Program)Breakthrough Montessori PCS\xa0 Center City PCS \u2013 Capitol HillKIPP DC PCS \u2013 Heights AcademyDC Scholars PCSCenter City PCS \u2013 PetworthShining Stars Montessori Academy PCSSomerset Preparatory Academy PCSInspired Teaching Demonstration PCSCreative Minds International PCSPaul PCS \u2013 Middle SchoolFriendship PCS-  Technology Preparatory AcademyKIPP DC PCS \u2013 AIM AcademyDC Preparatory Academy PCS \u2013 Edgewood ElementaryCarlos Rosario International PCSThurgood Marshall Academy PCSExcel Academy PCSAchievement Preparatory PCS \u2013 ElementaryFriendship PCS \u2013 Southeast Elementary AcademyLAYC Career Academy PCSKIPP DC \u2013 Heights Academy PCSKIPP DC PCS \u2013 Lead AcademyBASIS DC PCSKIPP DC \u2013 Quest Academy PCSKIPP DC \u2013 Connect Academy PCSSt. Coletta Special Education PCSThe Children's Guild DC PCSDC Prep PCS \u2013 Edgewood ElementaryAchievement Preparatory PCS \u2013 MiddleCesar Chavez PCS for Public Policy \u2013 Capitol HillKIPP DC PCS \u2013 Connect AcademyLee Montessori PCSDC International PCSKIPP DC \u2013 LEAP Academy PCSHope Community PCS \u2013 LamondWashington Leadership Academy PCSBridges PCSBASIS DC PCSFriendship PCS \u2013 Southeast AcademyElsie Whitlow Stokes Community Freedom PCS (Spanish Language Program)Mary McLeod Bethune Day Academy PCSDC Preparatory Academy PCS \u2013 Anacostia ElementaryWashington Latin PCS \u2013 Middle SchoolExcel Academy PCSKIPP DC \u2013 Spring Academy PCSCapital City PCS \u2013  MiddleKIPP DC \u2013 Arts and Technology PCSMaya Angelou PCS \u2013 Young Adult Learning CenterYouthbuild PCSCesar Chavez PCS for Public Policy \u2013 Parkside Middle SchoolIngenuity Prep PCSCenter City PCS \u2013 BrightwoodIngenuity Preparatory PCSAppleTree Early Learning PCS \u2013 SouthwestDemocracy Prep Congress Heights PCSCommunity College Preparatory PCSSela PCSKIPP DC \u2013 Discover Academy PCSWashington Global PCSBridges PCS - Special ClassroomPotomac Lighthouse PCSMeridian PCSPaul PCS \u2013 International High SchoolPerry Street Prep PCSKIPP DC PCS \u2013 Northeast AcademyCenter City PCS \u2013 ShawKIPP DC \u2013 KEY Academy PCSFriendship PCS \u2013 Technology Preparatory MiddleHospitality High PCSFriendship PCS \u2013 Woodridge MiddleShining Stars Montessori Academy PCSTwo Rivers PCS \u2013 4th StreetC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Parkside MiddleKIPP DC \u2013 AIM Academy PCSC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Chavez PrepBridges PCSBriya PCSFriendship PCS \u2013 Woodridge ElementaryLatin American Montessori Bilingual PCSHarmony DC PCS \u2013 School of ExcellenceFriendship PCS \u2013 Chamberlain MiddleThurgood Marshall Academy PCSCedar Tree PCSKIPP DC \u2013 Promise Academy PCSPaul PCS \u2013 Middle SchoolNext Step/El Proximo Paso PCSCapital City PCS \u2013 LowerKIPP DC PCS \u2013 LEAP AcademyCedar Tree Academy PCSSEED PCS of Washington, DCFriendship PCS \u2013 Blow-Pierce ElementaryKIPP DC PCS \u2013 KEY AcademyWashington Latin PCS \u2013 Upper SchoolElsie Whitlow Stokes Community Freedom PCSFriendship PCS \u2013 ArmstrongDemocracy Prep Congress Heights PCSAppleTree Early Learning PCS \u2013 Oklahoma AveTwo Rivers PCSCommunity Academy PCS \u2013 Butler GlobalCapital City PCS \u2013 HighHope Community PCS \u2013 TolsonWashington Yu Ying PCSAppleTree Early Learning PCS \u2013 SoutheastLee Montessori PCSAppleTree Early Learning PCS \u2013 OklahomaMaya Angelou PCS \u2013 High SchoolCenter City PCS \u2013 Congress HeightsMary McLeod Bethune Day Academy PCSKIPP DC PCS \u2013 College Preparatory AcademyIDEA (Integrated Design and Electronics Academy) PCSCenter City PCS \u2013 TrinidadKIPP DC PCS \u2013 Spring AcademyKIPP DC PCS \u2013 Promise AcademyCapital City PCS \u2013 UpperFriendship PCS \u2013 Blow-Pierce MiddleC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Parkside HighLatin American Montessori Bilingual PCSHoward University Middle School of Math and Science PCSAchievement Preparatory Academy PCS \u2013 ElementaryFriendship PCS \u2013 Woodridge MiddleMundo Verde Bilingual PCSKIPP DC PCS \u2013 Discover AcademyIdeal Academy PCSKIPP DC PCS \u2013 Valor AcademyFriendship PCS \u2013 Collegiate AcademyCenter City PCS \u2013 ShawBriya PCSMonument Academy PCSE.L. Haynes PCS \u2013 MiddleSomerset Preparatory Academy PCSHoward University Middle School of Mathematics and Science PCSKIPP DC \u2013 Grow Academy PCSAppleTree Early Learning PCS \u2013 Lincoln ParkCreative Minds International PCSCenter City PCS \u2013 Capitol HillCesar Chavez PCS for Public Policy \u2013 Chavez PrepCenter City PCS \u2013 PetworthAppleTree Early Learning PCS \u2013 SoutheastAppleTree Early Learning PCS \u2013 SouthwestFriendship PCS  \u2013 Chamberlain MiddleDC Prep PCS \u2013 Benning ElementaryE.L. Haynes PCS \u2013 Kansas Avenue (Elementary School)Hope Community PCS \u2013 LamondTree of Life PCSDistrict of Columbia International School (Chinese Language Program)Options PCSExcel Academy PCSFriendship PCS \u2013 Blow-Pierce ElementaryEagle Academy PCS \u2013 Capitol RiverfrontEagle Academy PCS \u2013 The Eagle Center at McGogneyE.L. Haynes PCS \u2013 ElementaryKIPP DC PCS \u2013 Arts & Technology AcademyAppleTree Early Learning PCS \u2013 Columbia HeightsEarly Childhood Academy PCSRoots PCSCommunity Academy PCS \u2013 Amos 2District of Columbia International School (French Language Program)Friendship PCS \u2013 Chamberlain ElementaryE.L. Haynes PCS \u2013 HighDC Preparatory Academy PCS \u2013 Edgewood MiddleNational Collegiate Preparatory PCHSCapital City PCS \u2013 MiddleCenter City PCS \u2013 Congress HeightsEarly Childhood Academy PCSKIPP DC PCS \u2013 Grow AcademyWashington Latin PCS \u2013 Upper SchoolPerry Street Preparatory PCSHarmony DC PCSFriendship PCS \u2013 Woodridge ElementaryDC Prep PCS \u2013 Benning MiddleIdeal Academy PCSDC Bilingual PCSFriendship PCS \u2013 Chamberlain ElementaryE.L. Haynes PCS \u2013 Georgia AvenueAchievement Preparatory Academy PCS \u2013 MiddleMaya Angelou PCS \u2013 Evans High SchoolKIPP DC \u2013 Northeast Academy PCSInspired Teaching Demonstration PCSWashington Yu Ying PCSCity Arts & Prep PCSCommunity Academy PCS \u2013 Amos 1Two Rivers PCS \u2013 YoungEagle Academy PCS \u2013 New Jersey AvenueE.L. Haynes PCS \u2013 Kansas Avenue (High School)Friendship PCS \u2013 Collegiate AcademyMeridian PCSDC Preparatory Academy PCS \u2013 Benning MiddleKIPP DC PCS \u2013 Quest AcademyC\xe9sar Ch\xe1vez PCS for Public Policy \u2013 Capitol HillFriendship PCS \u2013 OnlineCenter City PCS \u2013 Trinidad"

In [10]:
chi_charter.total_number_of_names_on_the_wait_list.sum()

TypeError: coercing to Unicode: need string or buffer, int found

In [18]:
chi_charter["number_of_names"] = pd.to_numeric(chi_charter["total_number_of_names_on_the_wait_list"], errors="coerce")

In [20]:
chi_charter.number_of_names.sum()

58213.0

TypeError: unsupported operand type(s) for +: 'int' and 'unicode'